// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


public static class GameObjectHelper
{
	
	public static T GetChildrenByName<T>(this GameObject gameObject, string name) where T : UnityEngine.Object
	{
		var children = gameObject.GetComponentsInChildren<T>();
		foreach (var item in children) {
			if(item.name==name)
			{
				return item;
			}
		}
		
		return null;
	}
}