// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Level
{
	public string Name {
		get;
		set;
	}

	public string Title {
		get;
		set;
	}

	public bool Completed {
		get;
		set;
	}

	public int CompletedWithStarsCount
	{
		get;
		set;
	}

	public bool CurrentCompleted {
		get;
		set;
	}
}


